version: "3.9"
services:
  todoui:
    image: desertmark/todoui:latest
    ports:
      - "80:80"
    networks:
      - todo

  todoservice:
    image: desertmark/todoservice:latest
    ports:
      - "5001:5001"
    networks:
      - todo

networks:
  todo:
    external: true
